### ISSUE TITLE
Remove extra ,

### ISSUE THREAD

**Issue by broekieman** [mr-manuel/venus-os_dbus-mqtt-pv#41]
```yml
alias: mqtt publish sensor pv power
description: ""
trigger:
  - platform: state
    entity_id: sensor.YOUR_PV_POWER_ENTITY
condition: []
action:
  - service: mqtt.publish
    data_template:
      payload: |
        {
          "pv": {
            "power": {{ (states('sensor.YOUR_PV_POWER_ENTITY') | float(0)) }},
            "L1": {
                "power": {{ (states('sensor.YOUR_PV_L1_POWER_ENTITY') | float(0)) }}`,`
            },
            "L2": {
                "power": {{ (states('sensor.YOUR_PV_L2_POWER_ENTITY') | float(0)) }}`,`
            },
            "L3": {
                "power": {{ (states('sensor.YOUR_PV_L3_POWER_ENTITY') | float(0)) }}`,`

            }
          }
        }
      topic: homeassistant/energy/pv
```
