### ISSUE TITLE
Not show total sun

### ISSUE THREAD

**Issue by broekieman** [mr-manuel/venus-os_dbus-mqtt-pv#57]
Is it not possible to show total sun? 

![Image](https://github.com/user-attachments/assets/67b8e130-13d8-4e88-a293-9ca91a2e3da8)

**Comment by mr-manuel** [comment]
You have to provide energy forward for that.

**Comment by broekieman** [comment]
Is this a setting, please explain.

**Comment by mr-manuel** [comment]
Read the README and check the [full JSON structure](https://github.com/mr-manuel/venus-os_dbus-mqtt-pv#json-structure).

**Comment by broekieman** [comment]
We solved this code for homeassistant together(missed a komna) I have pv data in my screenshot but Totaal stays zero.

**Comment by RandomVictronUser** [comment]
Just to let you know. Your issue is no problem here.

**Comment by broekieman** [comment]
> Just to let you know. Your issue is no problem here.

You mean, you have also enphase standaar and the script and you get field total filled?

**Comment by mr-manuel** [comment]
Why are you not using directly the Enphase driver in my repository?

**Comment by RandomVictronUser** [comment]
> > Just to let you know. Your issue is no problem here.
> 
> You mean, you have also enphase standaar and the script and you get field total filled?

Yup. Enphase Envoy, Relay and IQ8 micro’s.

**Comment by broekieman** [comment]
> > > Just to let you know. Your issue is no problem here.
> > 
> > 
> > You mean, you have also enphase standaar and the script and you get field total filled?
> 
> Yup. Enphase Envoy, Relay and IQ8 micro’s.

Envoy standard or envoy metered?

**Comment by RandomVictronUser** [comment]
> Why are you not using directly the Enphase driver in my repository?

For me that is due to the fact that I use the Envoy Gateway S. Not a metered Envoy gateway. Next to a couple of IQ8’s that are still coupled via HomeWizard Energy Plugs.

**Comment by RandomVictronUser** [comment]
> > > > Just to let you know. Your issue is no problem here.
> > > 
> > > 
> > > You mean, you have also enphase standaar and the script and you get field total filled?
> > 
> > 
> > Yup. Enphase Envoy, Relay and IQ8 micro’s.
> 
> Envoy standard or envoy metered?

Enphase Gateway S (new name). Not a metered one.

**Comment by RandomVictronUser** [comment]
> Please show your photo like mine.

![Image](https://github.com/user-attachments/assets/186b4c79-e6a8-4e34-bee7-1be97247de38)

**Comment by broekieman** [comment]
So you do not have ct clamps?

**Comment by RandomVictronUser** [comment]
Not for the Enphase Gateway Standard in a shed. Only for the new Victron Energy meter. Which works with CT’s as you may know. 

But how is your JSON configured? My guess is that there is some omission or error. Have you checked cat /data/log/dbus-mqtt-pv/current and view -> debug messaged?

**Comment by broekieman** [comment]
Do you mean json in home assstant?
Please share yours.

**Comment by broekieman** [comment]
I do not have the fles current and view.

**Comment by RandomVictronUser** [comment]
Sorry. I don't use Home Assistant (as in not yet) and my data won't help you either.

**Comment by broekieman** [comment]
Still you are using this plugin and receive data in the venus.

**Comment by broekieman** [comment]
Please tell me which envoy sensors i need for 1 phase installation.

payload: |
        {
          "pv": {
            "power": {{ (states('sensor.YOUR_PV_POWER_ENTITY') | float(0)) }},
            "L1": {
                "power": {{ (states('sensor.YOUR_PV_L1_POWER_ENTITY') | float(0)) }}

**Comment by mr-manuel** [comment]
I can't know how the sensor in your system is named. You need to add the lifetime produced energy as `energy_forward`.

**Comment by broekieman** [comment]
I was forgotten the username/password.
It's working now.
I have 1 phase enphase system on L1.
What do i need to get the total filled?

![Image](https://github.com/user-attachments/assets/d948efe2-2d70-4dee-aed1-b823881352c9)

Is my j.son ok?

{
  "pv": {
    "power": {{ (states('sensor.envoy_122248025029_current_power_production') | float(0)) }},
    "L1": {
        "power": {{ (states('sensor.envoy_122248025029_current_power_production') | float(0)) }}
    }
  }
}

**Comment by RandomVictronUser** [comment]
You need to add the  “energy_forward:” total_energy property, where the latter represents the total production data of the envoy. I use total_energy = Math.trunc(energy);

**Comment by broekieman** [comment]
Is this correct?

``
params:
  domain: mqtt
  service: publish
  service_data:
    payload: |-
      {
        "pv": {
          "power": 0.0,
          "L1": {
              "power": 0.0
        "Energy forward": {
          "power": 11051784.0  
          }
        }
      }
    topic: homeassistant/energy/pv
``

**Comment by mr-manuel** [comment]
What are you using to get the PV data into home assistant? Would be better, if you ask there for help.

**Comment by RandomVictronUser** [comment]
> Yes i have D8 firmware but i do not understand how to add the énergy_forward:'total_energy property. Can you share an example?

I think that you need to add a similar line like you have for wattage, but then replace the current_power_production with Lifetime_energy_production

Again. I do not use HomeAssistant so this is my best guess. Sorry if that doesn’t work. Share JSON when it fails or works. Thanks.

**Comment by broekieman** [comment]
I read following in py file:

 if "energy_forward" in jsonpayload["pv"]["L1"]:
                                    pv_L1_forward = float(jsonpayload["pv"]["L1"]["energy_forward"])

How does this look like in j.son when only having L1 configured?

**Comment by mr-manuel** [comment]
I don't know what you don't get, but here is everything listed again:

Needed JSON payload as written in the README that the driver needs to display correctly in VRM:

```json
{
    "pv": {
        "power": 0.0,
        "energy_forward": 0.0
    }
}
```

OR

```json
{
    "pv": {
        "power": 0.0,
        "energy_forward": 0.0,
        "L1": {
            "power": 0.0,
            "energy_forward": 0.0
        }
    }
}
```

Possible Home Assistant config (out of scope of this repository):

```yml
alias: mqtt publish sensor pv power
description: ""
trigger:
  - platform: state
    entity_id: sensor.YOUR_PV_POWER_ENTITY
condition: []
action:
  - service: mqtt.publish
    data_template:
      payload: |
        {
          "pv": {
            "power": {{ (states('sensor.YOUR_PV_POWER_ENTITY') | float(0)) }},
            "energy_forward": {{ (states('sensor.YOUR_PV_LIFETIME_PRODUCTION_IN_KWH') | float(0)) }},
            "L1": {
                "power": {{ (states('sensor.YOUR_PV_L1_POWER_ENTITY') | float(0)) }}
                "energy_forward": {{ (states('sensor.YOUR_PV_LIFETIME_PRODUCTION_IN_KWH') | float(0)) }}
            }
          }
        }
      topic: homeassistant/energy/pv
```

OR


```yml
alias: mqtt publish sensor pv power
description: ""
trigger:
  - platform: state
    entity_id: sensor.YOUR_PV_POWER_ENTITY
condition: []
action:
  - service: mqtt.publish
    data_template:
      payload: |
        {
          "pv": {
            "power": {{ (states('sensor.YOUR_PV_POWER_ENTITY') | float(0)) }},
            "energy_forward": {{ (states('sensor.YOUR_PV_LIFETIME_PRODUCTION_IN_KWH') | float(0)) }}
          }
        }
      topic: homeassistant/energy/pv
```

Maybe this could also help you: https://github.com/Matthew1471/Enphase-API

How you get the data from your device and how you build it in Home Assistant is out of the scope of this repository.
